AIM/AIM/AIM.Web.Admin/Controllers/OpenJobController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AIM.Service.Entities.Models;
using AIM.Web.Admin.JobServiceReference;

namespace AIM.Web.Admin.Controllers
{
    public class OpenJobController : Controller
    {
        private JobServiceClient _client = new JobServiceClient();

        // GET: /OpenJob/
        public ActionResult Index()
        {
            var regions = _client.GetRegionList();
            return View(regions.ToList());
        }

        public ActionResult StoreSelect(string RegionId)
        {
            int id = Convert.ToInt32(RegionId);
            var stores = _client.GetStoreList(id);
            return View(stores.ToList());
        }

        public ActionResult OpenJobList(string StoreId)
        {
            int id = Convert.ToInt32(StoreId);
            var openJobs = _client.GetOpenJobsForStore(id);
            return View(openJobs.ToList());
        }



        // GET: /OpenJob/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenJob openjob = db.OpenJobs.Find(id);
            if (openjob == null)
            {
                return HttpNotFound();
            }
            return View(openjob);
        }

        /*
        // GET: /OpenJob/Create
        public ActionResult Create()
        {
            ViewBag.jobId = new SelectList(db.Jobs, "jobId", "position");
            ViewBag.regionId = new SelectList(db.Regions, "regionId", "regionName");
            ViewBag.storeId = new SelectList(db.Stores, "storeId", "name");
            return View();
        }

        // POST: /OpenJob/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="openJobsId,jobId,storeId,regionId,isApproved")] OpenJob openjob)
        {
            if (ModelState.IsValid)
            {
                db.OpenJobs.Add(openjob);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.jobId = new SelectList(db.Jobs, "jobId", "position", openjob.jobId);
            ViewBag.regionId = new SelectList(db.Regions, "regionId", "regionName", openjob.regionId);
            ViewBag.storeId = new SelectList(db.Stores, "storeId", "name", openjob.storeId);
            return View(openjob);
        }

        // GET: /OpenJob/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenJob openjob = db.OpenJobs.Find(id);
            if (openjob == null)
            {
                return HttpNotFound();
            }
            ViewBag.jobId = new SelectList(db.Jobs, "jobId", "position", openjob.jobId);
            ViewBag.regionId = new SelectList(db.Regions, "regionId", "regionName", openjob.regionId);
            ViewBag.storeId = new SelectList(db.Stores, "storeId", "name", openjob.storeId);
            return View(openjob);
        }

        // POST: /OpenJob/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="openJobsId,jobId,storeId,regionId,isApproved")] OpenJob openjob)
        {
            if (ModelState.IsValid)
            {
                db.Entry(openjob).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.jobId = new SelectList(db.Jobs, "jobId", "position", openjob.jobId);
            ViewBag.regionId = new SelectList(db.Regions, "regionId", "regionName", openjob.regionId);
            ViewBag.storeId = new SelectList(db.Stores, "storeId", "name", openjob.storeId);
            return View(openjob);
        }

        // GET: /OpenJob/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenJob openjob = db.OpenJobs.Find(id);
            if (openjob == null)
            {
                return HttpNotFound();
            }
            return View(openjob);
        }

        // POST: /OpenJob/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OpenJob openjob = db.OpenJobs.Find(id);
            db.OpenJobs.Remove(openjob);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
         
         */
    }
}

AIM/AIM/AIM.Web.Admin/Views/OpenJob/Delete.cshtml
@model AIM.Service.Entities.Models.OpenJob

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OpenJob</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Job.position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Job.position)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Region.regionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Region.regionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Store.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Store.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isApproved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isApproved)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AIM/AIM/AIM.Web.Admin/Views/OpenJob/Details.cshtml
@model AIM.Service.Entities.Models.OpenJob

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>OpenJob</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Job.position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Job.position)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Region.regionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Region.regionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Store.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Store.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isApproved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isApproved)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.openJobsId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AIM/AIM/AIM.Web.Admin/Views/OpenJob/Index.cshtml
@model IEnumerable<AIM.Service.Entities.Models.Region>

@{
    ViewBag.Title = "Index";
}

<h2>Region Select</h2>

<center>
    @using (Html.BeginForm("StoreSelect", "OpenJob", FormMethod.Get))
    {
        <fieldset>
           Select region: <select name="RegionId">
                @foreach (var item in Model)
                {
                    <option value=@item.regionId>@item.regionName</option>
                }
            </select>
            <p>
                <input type="submit" value="Submit" class="btn btn-success" />
            </p>
        </fieldset>
    }
</center>

AIM/AIM/AIM.Web.Admin/Views/OpenJob/OpenJobList.cshtml
@model IEnumerable<AIM.Service.Entities.Models.OpenJob>

@{
    ViewBag.Title = "OpenJobList";
}

<h2>Job Opening Requests</h2>

<table class="table">
    <tr>
        <th></th> <!-- Details button column -->
        <th>
            @Html.DisplayNameFor(model => model.Job.position)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Store.name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a class="btn btn-success" href="@Url.Action("Details", "OpenJob", new { id = item.openJobsId })">
                    <i class="icon-zoom-in icon-white"></i>
                    Details
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Job.position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Store.name)
            </td>
        </tr>
    }

</table>
<p>
    
</p>

AIM/AIM/AIM.Web.Admin/Views/OpenJob/StoreSelect.cshtml
@model IEnumerable<AIM.Service.Entities.Models.Store>

@{
    ViewBag.Title = "Store Select";
}

<h2>Store Select</h2>

<center>
    @using (Html.BeginForm("OpenJobList", "OpenJob", FormMethod.Get))
    {
        <fieldset>
            Select store: <select name="StoreId">
                @foreach (var item in Model)
                {
                    <option value=@item.storeId>@item.name</option>
                }
            </select>
    
            <p>
                <input type="submit" value="Submit" class="btn btn-success" />
            </p>
        </fieldset>
    }
</center>